### ISSUE TITLE
Value reported in real or nominal terms?

### ISSUE THREAD

**Issue by rmgriffin** [ropensci/seaaroundus#32]
I did not see anything in the documentation regarding the format of the revenue values represented here. In downloading data from the searoundus website, the methods document states the below quoted content which seems to indicate it is nominal data when downloaded from there, though interestingly no revenue data seems to currently be downloadable from the website so I cannot compare. Any clarification would be appreciated. Thanks!
Rob

> The primary data in the database are nominal ex-vessel prices as obtained, in most cases by dividing officially reported landed values by landings. Ex-vessel prices and landed values are presented in US$ to allow a uniform basis for comparison. However, the starting point for the data is always local ex-vessel prices in local currency, which are converted into US$ equivalents.
>                               
> There are two parallel parts to the database, namely, ‘nominal’ and ‘real’ ex-vessel prices and landed values. The ‘real’ numbers were determined by using local consumer price indices (CPI, obtained from the World Bank) to convert local ‘nominal’ ex-vessel prices into ‘real’ ex-vessel prices using the year 2005 as basis. These are then converted into year 2005 US$ equivalents.

**Comment by sckott** [comment]
@Gtsui091 @LinhTran any thoughts on this?

**Comment by Gtsui091** [comment]
@rmgriffin Hi Rob, the values are the 'real' values for 2010 US$ equivalents.
It appears the methods are out of date. The latest methods can be found here http://www.seaaroundus.org/catch-reconstruction-and-allocation-methods/#_Toc421534369.

The current value the data is currently not available on the website because we are in the process of updating all the data to 2016 so it has been temporarily disabled. It will be ready for download again by the end of December.

**Comment by rmgriffin** [comment]
Awesome, thanks for clarifying and providing this data
